// apps/ui/src/App.svelte
<script lang="ts">
    import Route from '$lib/components/Route.svelte';
    import Router from '$lib/components/Router.svelte';
    import Runtime from '$lib/components/Runtime.svelte';
    import { createMessenger } from '$lib/services/messenger';
    import { createRouter } from '$lib/services/router';
</script>

{#if mp.isBrowser}
    <div class="fixed inset-0 bg-green-500"></div>
{/if}
<Runtime messenger={createMessenger()} router={createRouter()}>
    <Router>
        {#snippet children(routes)}
            {#each Object.entries(routes) as [route, importModule] (route)}
                {#await importModule().then((a) => a.default) then Component}
                    <Route {route}>
                        <Component />
                    </Route>
                {/await}
            {/each}
        {/snippet}
    </Router>
</Runtime>

// apps/ui/src/App.tsx
import { Route } from '$lib/components/Route';
import { useRuntime } from '$lib/contexts/runtime-context';
import { AnimatePresence } from 'framer-motion';
import { lazy, Suspense } from 'react';

export default function App() {
  const { router } = useRuntime();

  return (
    <AnimatePresence initial={true}>
      {mp.isBrowser && <div className="fixed inset-0 bg-green-500"></div>}
      {Array.from(router.routes.entries()).map(([key, props]) => {
        const Component = lazy(() => import(`./routes/${key}/Index.tsx`));
        return (
          <Suspense key={key}>
            <Route name={key}>
              <div className="fixed">
                <Component {...(props ?? {})} />
              </div>
            </Route>
          </Suspense>
        );
      })}
    </AnimatePresence>
  );
}
