// apps/ui/src/lib/components/Route.svelte
<script lang="ts">
    import { onMount, type Snippet, type SvelteComponent } from 'svelte';
    import { useRuntime } from '$lib/services/runtime';

    const {
        route,
        children,
    }: {
        route: string;
        children: Snippet;
    } = $props();

    const { messenger } = useRuntime();

    onMount(() => {
        messenger.publish('router.mount', route);
        return () => {
            messenger.publish('router.unmount', route);
        };
    });
</script>

{@render children()}

// apps/ui/src/lib/components/Route.tsx
import { useRuntime } from '$lib/contexts/runtime-context';
import { useEffect, type ReactNode } from 'react';

export const Route = ({ name, children }: { name: string; children: ReactNode }) => {
  const { messenger } = useRuntime();
  //   const ref = useRef(false);

  useEffect(() => {
    // if (ref.current) return;
    // ref.current = true;
    console.log('ui.router.mount', name);
    messenger.publish('ui.router.mount', name);
    return () => {
      console.log('ui.router.unmount', name);
      messenger.publish('ui.router.unmount', name);
    };
  }, []);

  return <>{children}</>;
};
